{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='3'/}
{dede:img ddimg='/uploads/allimg/150702/1-150F2102547.jpg' text='' width='500' height='500'} /uploads/allimg/150702/1-150F2102547.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150702/1-150F2102553.jpg' text='' width='900' height='900'} /uploads/allimg/150702/1-150F2102553.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150702/1-150F2102557.jpg' text='' width='900' height='900'} /uploads/allimg/150702/1-150F2102557.jpg {/dede:img}
